# Generated by Django 3.2.13 on 2023-08-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdoluis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filmes',
            new_name='Movies',
        ),
    ]
